on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["windows-latest", "ubuntu-latest", "macos-latest"]

    steps:
      - uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10.11"
          cache: "poetry"

      - name: Install libxcb and libxkb
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y libxcb* libxkb*

      - name: Install dependencies
        run: poetry install

      - name: Build
        run: poetry run pyinstaller --onefile --name tda-generate-token-${{ matrix.os }} app/__main__.py

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
