on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["windows-latest", "ubuntu-latest", "macos-latest"]

    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10.12"
          cache: "poetry"
      - run: poetry install
      - run: poetry run pyinstaller app/__main__.py
      - uses: actions/upload-artifact@v3
        with:
          path: dist/*
